openapi: 3.0.3
info:
  version: 1.0.0
  title: OpenAPIStudent
  description: OpenAPIStudent realized with OpenAPI
servers:
  - url: http://localhost:8080/
tags:
  - name: students
    description: Operations on students
paths:
  /keepalive:
    get:
      tags:
        - students
      summary: Student Keepalive
      description: Keepalive route for the student com.salatino.andrea.openapidemo.controller
      operationId: keepAlive
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
  /:
    get:
      tags:
        - students
      summary: Retrieve students
      description: Get all the student objects
      operationId: getStudents
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
        404:
          description: No data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
components:
  schemas:
    Student:
      type: object
      properties:
        serialNumber:
          type: string
        name:
          type: string
        surname:
          type: string
        dateOfBirth:
          type: string
          format: date
        cf:
          type: string
    Students:
      type: array
      items:
        $ref: "#/components/schemas/Student"
    BaseError:
      type: object
      required:
        - code
      properties:
        code:
          type: integer
          format: int32